// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Wallet struct {
	ID         int32
	Uuid       uuid.UUID
	UserID     uuid.UUID
	BalanceUsd string
	BalanceRub string
	BalanceEur string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
