// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id) VALUES ($1)
    RETURNING id, uuid, user_id, balance_usd, balance_rub, balance_eur, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.BalanceUsd,
		&i.BalanceRub,
		&i.BalanceEur,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, uuid, user_id, balance_usd, balance_rub, balance_eur, created_at, updated_at
FROM wallets
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.BalanceUsd,
		&i.BalanceRub,
		&i.BalanceEur,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEURBalance = `-- name: UpdateEURBalance :exec
UPDATE wallets
SET balance_eur = balance_eur + CAST($1 AS NUMERIC(18,2)),
    updated_at = now()
WHERE user_id = $2
`

type UpdateEURBalanceParams struct {
	Amount string
	UserID uuid.UUID
}

func (q *Queries) UpdateEURBalance(ctx context.Context, arg UpdateEURBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateEURBalance, arg.Amount, arg.UserID)
	return err
}

const updateRUBBalance = `-- name: UpdateRUBBalance :exec
UPDATE wallets
SET balance_rub = balance_rub + CAST($1 AS NUMERIC(18,2)),
    updated_at = now()
WHERE user_id = $2
`

type UpdateRUBBalanceParams struct {
	Amount string
	UserID uuid.UUID
}

func (q *Queries) UpdateRUBBalance(ctx context.Context, arg UpdateRUBBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateRUBBalance, arg.Amount, arg.UserID)
	return err
}

const updateUSDBalance = `-- name: UpdateUSDBalance :exec
UPDATE wallets
SET balance_usd = balance_usd + CAST($1 AS NUMERIC(18,2)),
    updated_at = now()
WHERE user_id = $2
`

type UpdateUSDBalanceParams struct {
	Amount string
	UserID uuid.UUID
}

func (q *Queries) UpdateUSDBalance(ctx context.Context, arg UpdateUSDBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUSDBalance, arg.Amount, arg.UserID)
	return err
}
