// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    user_id,
    balance
) VALUES (
    $1,
    '0.00'
) RETURNING id, uuid, user_id, balance, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT balance FROM wallets
WHERE user_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getWalletBalance, userID)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, uuid, user_id, balance, created_at, updated_at FROM wallets 
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets
SET 
    balance = CAST(balance AS DECIMAL(18,2)) + CAST($1 AS DECIMAL(18,2)),
    updated_at = now()
WHERE user_id = $2
`

type UpdateWalletBalanceParams struct {
	Amount string
	Userid uuid.UUID
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateWalletBalance, arg.Amount, arg.Userid)
	return err
}
