# .env file example
# PORT=8080
# DB_URL=postgres://postgres:postgres@db:5432/wallet?sslmode=disable
# POSTGRES_USER=postgres
# POSTGRES_PASSWORD=postgres
# POSTGRES_DB=wallet
services:
  db:
    image: postgres:15
    container_name: gw-wallet-db
    networks:
      - shared-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gw-wallet
    networks:
      - shared-network
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["/app/wait-for-db.sh", "db", "/app/entrypoint.sh"]

volumes:
  postgres_data:

networks:
  shared-network:
    external: true